//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameNet_Management.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public int SessionID { get; set; }
        public int CustomerID { get; set; }
        public int OptionID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> TotalMinutes { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> DeviceID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Devices Devices { get; set; }
        public virtual ServiceOptions ServiceOptions { get; set; }
    }
}
